language: ruby
before_install:
- rvm install 2.4.1
rvm:
- 2.2
- 2.4.1
script:
- rake
- yardoc lib/*  --output-dir docs
env:
  global:
    secure: cIUR+8Yf+g1Ta3rRhp6rnnBSDDJVEKk9QY8+GsynUt02sHsJrcxLuAHwHvbmcMPnoXx1SXZkYi/ETK3JrrnvTgqy8gYeJvXmHvO77OneznJeD6f0uZC1oPnmiceiprtc3BLcus1MRhdqTy8SjUE8/MOELhTwB6d6gkeDhLXNQO5DJTlVpvf0nNYErS7Ono5rS23Olpb9QCREpJBbE9uYj9r6mho5xY3cD6idXYvKmgBWgklXGa+ja76XwPxDewTCu6J7cRulg7T0K4EnmvqvLqlIvNSi4k9kmc+ImisjlrCwbegfc8Af5e/k0QvOP6sZArqAAb/NdzX6HMxARv+5PA5GIQWH/hqQOCFQR3o5eSFYN/ssBkCTKARIrCxjetyj9s7Jp8zO9XVvAjiFaYM9cw4kQsnzrL2S8tRhjsFzrWymARScT30N++ORU/emfDzAK9zj5gAZtUuUMJyo42FC1FG0KXV+2yAuFAdX01fY5NjobAbxwkvk8xOWWRuNwAb+6Fnhl+H1OA3FSce6HNlSAgB5oyHBtT6rLcBFTdHgK2HG8OoOn9PfwgVmGTQPgw5as0V6wRNAp/4qrmNJ1WGr8ZrvTyjGStl6Zb7mZ0HptLQ+JEsZOK6EE6vsH9I6pfkxi21Hc6/laiclIQva4+J8MyhTy1oJo9Enp1fAoDgYGLA=
