language: ruby
before_install:
- rvm install 2.4.1
rvm:
- 2.2
- 2.4.1
script:
- rake
- yardoc lib/*  --output-dir docs
env:
  global:
    secure: MFstob2cMsRBsb3MViMekkPf1HTxemKXpwpJ0p3Aw2eewg9OwiJ2LHaCceRUMng3GNLU9dIp8T0COFjmaFiEA5StLMZ+Q8hDARJVe8fHxqJVHK53jzfFPyIrnHcbnCMslzACZukit4wNwhmPRNbCYWfVUIScXJj9G5jf4fKTfOulwwY6KhEnM0XaP0XcNeVcAVFzjMUH6QygFlFjbSfbLdQOq4Ut2y8cU2tSV00Hgz/t2oQGti/W73EjUvwJCvo28F5bWeTAYs4yo5x7UPU0AwufCgajk5tIaxGASYudAnK1PFGe1/IVpP2c1s/4zQ8Axf+7K1VIP+yKizhFB2u512BysfIeGnJc1E/+wTSAOqfRJfBSgGuNipGA0kU9HFQ01yZOXvPyMhNL8XFp5WzPVMPLiFZZNZDclyYYl6D4oy0g2r9ZiXcAKgtsKevW3yGqkE3VvDJwKqTKBVD7hByLT5spj3TFNqH67rsowDZDM+zbXgJYYdZDK78K7sm+4NadNV+pDvHXamT0wv3YpcW73SxEwwlIJ5/KtWbQi3s4uOK+bGZIAADQjMY/2HZnkNOGppYamEjHql0ebbwHGia8U/l4g3L43ef2TEeI6BFb04VRopozMGGLq5DA4P/r/XYEDMKE6KQJP5+gGNfSBzAs+2Uoes52N39uUm83YaJ4tRQ=
