language: ruby
before_install:
- rvm install 2.4.1
rvm:
- 2.2
- 2.4.1
script:
- rake
- yardoc lib/*  --output-dir docs
env:
  global:
  - secure: Ur2BsfqnAdgXLZnBAYR+qIOcd+fGdMZ4/sYRHvEVvBU7nszWkzoHkscO5cxoc6zTgAQQHPwc2owe5PfNXlJFDZzvAvaH32hQoXj1zrRWTV3PW8kN1AzPRM+UNzIUtf4LDWISVWryHJvs4vWDFuOFB4Xn6UPjg6+/4mf4fsmS+o0LGctIEWvGhAp/3qaazdHmtBw64sUloPFJnfhVz4h4iEKgFwdre+we68Pgnto+Gjk2v8Xz0BW1v/TaVsLOPyHKVvzRju/zW+/eo6qo/vVxcNErV3Y6wdRJEWx+1g6QZDw5u6F6RLAPPjZQ/VRmwHnIV87Y+1C9Se5Gq5ZQnn4Fwj1d8yc5qyQI+e0bKfEPa5JU9oC/fs5gqR/yVzwnaYV4pmFThZCYrCeSOmvsqI5f8uvzBcWfuZeTGfNuSMXRy2Bkwn3vDxbaSQNm8xjOqxEOjVXf8MFdAfOVY8YXQGAr41INLeLOJr2LjQ3PsP9h812vwZieb/9Tf55CMAMAJpgz/3ktBjaNXkKv3kY7MidD+i6Y3zNmVUofm9ts03OtHdgcvl4DTQxyph7oipIc2+BrkSgbF3jXpMWLphuB0upWGIm33RTacgzrfgT9c0zdNBLOtd+g/UEbiNyJhm+qnX466xeGrosjU4MbHaDXcwk96omvqlz+/VkH7fr8xNMv2/Y=
