language: ruby
before_install:
- rvm install 2.4.1
rvm:
- 2.2
- 2.4.1
script:
- rake
- yardoc lib/*  --output-dir docs
env:
  global:
  - secure: ql/VCbflrObhpOxEJInoNmTQM/423IxuaMWsKAAA6dDBqI8/nZLi33S4NelmYTYDWidx4pHVvpvZnFn1Ej2V0HAnNC132+tUxD4CYyU6eBXS3hWSS5UuApzBlOEGjfb+8knid4rsfCNYX/mcPhl2HSxTaciIXC87y0cMc2aCP8Cf7/HYX++cvVLAXHLps3xKR2UQRPd83nwON68X+u1bKrdiJ+TpXF7VGNdnkAnjjXcFIcKCPjaoNhBUdJO4SNrj0EoOtTq29zQIW4LgLSWh2uHTmtgsmlFmrifKKS1dxS1hcubNkc0x52IMfLIowWbaHSSbZ50cniSxuGvnIzG3LXIyx+idDi1D5s3hAeADXG71JIi5UnlTSiteuncSaU5mgNMbBNDP1PEw6AcjZ9mA6U1veBup3yiRofuWQscmL4e6bq8JT7d3RYjPOymB9p/bySxXIqQ1z5sOqqkjb8gDF4sTgTxNlsvYMAvVdToTc6/WmPzaS6/6LCShM87Nmncj57PdJ/qydGAONPKq4zl09qSXTCWWnc2mq0vSmgSsPrUsQO0thrVNxTvR2WBO+PvyfLMrY5C7rkyLAcGmVXT8a7xYKv4urx5NKX9qk5+bytncq0Vy82EhdYkPJDfWYJ7ixXCzbAkAgpR1srBeItJWT717IFAomGQqqlzyFSBSMWI=
