language: ruby
branches:
  only:
    - master
before_install:
- openssl aes-256-cbc -K $encrypted_a30fbaed9b64_key -iv $encrypted_a30fbaed9b64_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- chmod 0600 travis_rsa
- cp travis_rsa ~/.ssh/id_rsa
- rvm install 2.4.1
rvm:
- 2.4.1
script:
- rake
- yardoc lib/*  --output-dir docs
after_success:
./deploy_docs
