language: ruby
branches:
  only:
    - master
before_install:
- openssl aes-256-cbc -K $encrypted_a30fbaed9b64_key -iv $encrypted_a30fbaed9b64_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- rvm install 2.5.0
rvm:
- 2.4.1
script:
- rake
- yardoc lib/*  --output-dir doc
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: doc
 on:
   branch: master
notifications:
  email:
    - marfachaiko@gmail.com