language: ruby
before_install:
- rvm install 2.4.1
rvm:
- 2.2
- 2.4.1
script:
- rake
- yardoc lib/*  --output-dir docs
env:
  matrix:
- secure: RgkZBb0Rudqc39ib5SNrLsVBbBD3toq9P/Zqj67CM1qA2QwBajZm9+meSXPgDxy0DnBHLHb6pHp2yIrW+zXQn26BsbSbNJhLcQTfUDcrFx/cgNZW9QiZOTVCuzrcBbxFjeHbOWgmIT6CmDIhASLqoYIGjhSSJBS1joYykJhfUYjL3Phq3vtu6ISDfF9mXKyrkmpZLme15gzOXdBGwNkuUA4qMOwSyfmNpNnWo5QrW7LeAxbilHsu7pKoojqmI+dxY/R4tLVvOdDMfErN5GTjFj1rUFo0JFqwnqEpDIlczGT9ktiHSeE8Kube4h4m5SE4cnc+111vpcCPGf3jx1ISx30nxXgeIvZn17ZRjHCNQlHn595VJgs6yCgY4lmUjU5t1J0kl8qV9twT8rIcc/lpM13BPZJXBueBRdSa50ntYOo5/OxwEzsAt1Us2fmtScDYg7dROsd0C1x/UbeFsqzYKnSPE2pyFzlNYSD6t3Ov7jXGCdYhMjFVXERjiCtozPVgHmMeeQGXo0FpVcK7Esq1ZPwBLjc07XQka/zeiljeP4bAkyNcMUoeZ3hLJyDjHCa+d/NHmkch4kS8QzJREehqeSTn+L5/G4COCpn8bwdA9GGuJCa+AAZYcYm955UKQN3ncE6nZsAGJTWN8+r3Sfi4SxYHVMsYwMxGLbp+7CZmjnE=
  global:
  - secure: RgkZBb0Rudqc39ib5SNrLsVBbBD3toq9P/Zqj67CM1qA2QwBajZm9+meSXPgDxy0DnBHLHb6pHp2yIrW+zXQn26BsbSbNJhLcQTfUDcrFx/cgNZW9QiZOTVCuzrcBbxFjeHbOWgmIT6CmDIhASLqoYIGjhSSJBS1joYykJhfUYjL3Phq3vtu6ISDfF9mXKyrkmpZLme15gzOXdBGwNkuUA4qMOwSyfmNpNnWo5QrW7LeAxbilHsu7pKoojqmI+dxY/R4tLVvOdDMfErN5GTjFj1rUFo0JFqwnqEpDIlczGT9ktiHSeE8Kube4h4m5SE4cnc+111vpcCPGf3jx1ISx30nxXgeIvZn17ZRjHCNQlHn595VJgs6yCgY4lmUjU5t1J0kl8qV9twT8rIcc/lpM13BPZJXBueBRdSa50ntYOo5/OxwEzsAt1Us2fmtScDYg7dROsd0C1x/UbeFsqzYKnSPE2pyFzlNYSD6t3Ov7jXGCdYhMjFVXERjiCtozPVgHmMeeQGXo0FpVcK7Esq1ZPwBLjc07XQka/zeiljeP4bAkyNcMUoeZ3hLJyDjHCa+d/NHmkch4kS8QzJREehqeSTn+L5/G4COCpn8bwdA9GGuJCa+AAZYcYm955UKQN3ncE6nZsAGJTWN8+r3Sfi4SxYHVMsYwMxGLbp+7CZmjnE=
