FROM ruby:2.0.0
MAINTAINER marfachaiko@gmail.com

# Install apt based dependencies required to run Rails as
# well as RubyGems. As the Ruby image itself is based on a
# Debian image, we use apt-get to install those.
RUN apt-get update && apt-get install -y \
  build-essential

# Configure the main working directory. This is the base
# directory used in any further RUN, COPY, and ENTRYPOINT
# commands.
RUN mkdir  /virgil-sdk-2.0.0
WORKDIR /virgil-sdk-2.0.0

# Copy the Gemfile as well as the Gemfile.lock and install
# the RubyGems. This is a separate step so the dependencies
# will be cached unless changes to one of those two files
# are made.
ADD lib /virgil-sdk-2.0.0/lib
ADD virgil-sdk.gemspec /virgil-sdk-2.0.0
ADD Gemfile /virgil-sdk-2.0.0
RUN gem install bundler && bundle install --jobs 20 --retry 5

ADD . /virgil-sdk-2.0.0